version: 2.1


jobs:
  hello:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: |
         echo hello world;
         echo $POSID;
         echo $POSI

workflows:
  workflow1:
    jobs:
      - hello:
          context:
            - circeci-test