version: 2.1

commands:
  build:
    parameters:
      stage:
        type: string
        default: development
    steps:
      - run: |
          echo ${<< parameters.stage >>}
jobs:
  hello:
    docker:
      - image: cimg/base:2023.02
    steps:
      - build:
          stage: << pipeline.git.branch >>
      - run: |
         echo << pipeline.git.branch >>
         echo hello world;
         echo $POSID;
         echo $POSI

workflows:
  workflow1:
    jobs:

      - hello:
          context:
            - circeci-test