version: 2.1


jobs:
  hello:
    docker:
      - image: cimg/base:2023.02
    steps:
      - checkout
      - run: |
         echo hello world;
         echo $POSID;
         echo $POSI
         echo $CIRCLE_BRANCH
         
         if [[ << pipeline.git.branch >> = "dev" ]]; then
          echo "it is dev o"
         else
          echo << pipeline.git.branch >>
         fi

workflows:
  workflow1:
    jobs:
      - hello:
          context:
            - circeci-test