version: 2.1


jobs:
  hello:
    docker:
      - image: cimg/base:latest
    steps:
      - checkout
      - run: |
         echo hello world;
         echo $POSID;
         echo $POSI

workflows:
  workflow1:
    jobs:
      - hello:
          context:
            - circeci-test